version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build1 started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build1 completed on `date`
      - aws cloudformation package --template-file samTemplate.yml --s3-bucket task7-image-bucket2 --output-template-file outputSamTemplate.yml
artifacts:
  files:
    - outputSamTemplate.yml