AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  LambdaApplication:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.epam.lambda.ImageUploadHandler::handleRequest
      Runtime: java11
      MemorySize: 512